# Generated by Django 4.2.9 on 2024-12-22 20:52

from django.db import migrations, models
import real_estate_broker.main_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=100, validators=[real_estate_broker.main_app.validators.IsItAPhoneNumber()]),
        ),
    ]
