# Generated by Django 4.2.9 on 2024-01-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personalinfo',
            options={'verbose_name': 'Personal Info', 'verbose_name_plural': 'Personal Infos'},
        ),
    ]
