# Generated by Django 4.2.9 on 2025-01-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Бургас', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Стоян Черелов', max_length=300),
        ),
    ]
