# Generated by Django 4.2.9 on 2026-03-25 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
