# Generated by Django 4.2.9 on 2026-03-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_comments_first_name_alter_comments_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='picture_url',
        ),
        migrations.AddField(
            model_name='comments',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='short_message',
            field=models.TextField(),
        ),
    ]
